name: Reusable workflow

on:
  workflow_call:

jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo contents
        uses: actions/checkout@v2
      - name: Run script
        run: ./runme.sh
